// typescript/native-auth/angular-sample/src/app/components/reset-password/reset-password.component.ts
import { Component } from "@angular/core";
import { AuthService } from "../../services/auth.service";
import {
    ResetPasswordCodeRequiredState,
    ResetPasswordPasswordRequiredState,
} from "@azure/msal-browser/custom-auth";
import { CommonModule } from "@angular/common";
import { FormsModule } from "@angular/forms";

@Component({
    selector: "app-reset-password",
    templateUrl: "./reset-password.component.html",
    styleUrls: ["./reset-password.component.scss"],
    standalone: true,
    imports: [CommonModule, FormsModule],
})
export class ResetPasswordComponent {
    email = "";
    code = "";
    newPassword = "";
    error = "";
    loading = false;
    showCode = false;
    showNewPassword = false;
    isReset = false;
    resetState: any = null;
    isSignedIn = false;
    userData: any = null;
    resendCountdown = 0;

    constructor(private auth: AuthService) {}

    async ngOnInit() {
        const client = await this.auth.getClient();
        const result = client.getCurrentAccount();
        if (result.isCompleted()) {
            this.isSignedIn = true;
            this.showCode = false;
            this.showNewPassword = false;
            this.isReset = false;
            this.userData = result.data;
        }
    }

    async startReset() {
        this.error = "";
        this.loading = true;
        this.isReset = false;
        this.showCode = false;
        this.showNewPassword = false;
        this.resetState = null;

        const client = await this.auth.getClient();
        const result = await client.resetPassword({ username: this.email });

        if (result.isFailed()) {
            this.error = result.error?.errorData?.errorDescription || "Password reset failed";
            if (result.error?.isInvalidUsername()) {
                this.error = "Invalid email address";
            } else if (result.error?.isUserNotFound()) {
                this.error = "User not found";
            } else {
                this.error =
                    result.error?.errorData?.errorDescription || "An error occurred while initiating password reset";
            }
        }

        this.resetState = result.state;

        if (result.isCodeRequired()) {
            this.showCode = true;
            this.isReset = false;
            this.showNewPassword = false;
        }

        this.loading = false;
    }

    async submitCode() {
        this.error = "";
        this.loading = true;
        if (this.resetState instanceof ResetPasswordCodeRequiredState) {
            const result = await this.resetState.submitCode(this.code);

            if (result.isFailed()) {
                if (result.error?.isInvalidCode()) {
                    this.error = "Invalid verification code";
                } else {
                    this.error =
                        result.error?.errorData.errorDescription || "An error occurred while verifying the code";
                }
            }

            if (result.isPasswordRequired()) {
                this.showCode = false;
                this.showNewPassword = true;
                this.isReset = false;
                this.resetState = result.state;
            }
        }
        this.loading = false;
    }

    async resendCode() {
        this.error = "";
        this.loading = true;

        if (this.resetState instanceof ResetPasswordCodeRequiredState) {
            const result = await this.resetState.resendCode();

            if (result.isFailed()) {
                this.error = result.error?.errorData?.errorDescription || "An error occurred while resending the code";
            } else {
                this.resendCountdown = 30;

                const timer = setInterval(() => {
                    this.resendCountdown--;
                    if (this.resendCountdown <= 0) {
                        clearInterval(timer);
                        this.resendCountdown = 0;
                    }
                }, 1000);
            }
        }

        this.loading = false;
    }

    async submitNewPassword() {
        this.error = "";
        this.loading = true;
        if (this.resetState instanceof ResetPasswordPasswordRequiredState) {
            const result = await this.resetState.submitNewPassword(this.newPassword);

            if (result.isFailed()) {
                if (result.error?.isInvalidPassword()) {
                    this.error = "Invalid password";
                } else {
                    this.error = result.error?.errorData.errorDescription || "An error occurred while setting new password";
                }
            }

            if (result.isCompleted()) {
                this.isReset = true;
                this.showNewPassword = false;
                this.showCode = false;
                this.resetState = result.state;
            }
        }
        this.loading = false;
    }
}

<div class="auth-container">
  <h2>Reset Password</h2>
  <div *ngIf="isSignedIn">
    <p>An user has signed in, please sign out first.</p>
  </div>
  <div *ngIf="isReset">
    <p>The password has been reset, please click <a href="/sign-in">here</a> to sign in.</p>
  </div>
  <form *ngIf="!showNewPassword && !showCode && !isSignedIn && !isReset" (ngSubmit)="startReset()">
    <input type="email" [(ngModel)]="email" name="email" placeholder="Email" required [readonly]="showCode || showNewPassword" />
    <button *ngIf="!showCode && !showNewPassword" type="submit" [disabled]="loading">{{ loading ? 'Resetting...' : 'Reset Password' }}</button>
  </form>
  <form *ngIf="showNewPassword" (ngSubmit)="submitNewPassword()">
    <input type="password" [(ngModel)]="newPassword" name="newPassword" placeholder="New Password" required />
    <button type="button" (click)="submitNewPassword()" [disabled]="loading">{{ loading ? 'Submitting...' : 'Submit New Password' }}</button>
  </form>
  <form *ngIf="showCode" (ngSubmit)="submitCode()">
    <input type="text" [(ngModel)]="code" name="code" placeholder="OTP Code" required />
    <button type="button" (click)="submitCode()" [disabled]="loading">{{ loading ? 'Verifying...' : 'Verify Code' }}</button>
    <button type="button" 
            (click)="resendCode()" 
            [disabled]="resendCountdown > 0"
            [class.resend-disabled]="resendCountdown > 0">
      {{ resendCountdown > 0 ? 'Resend Code (' + resendCountdown + 's)' : 'Resend Code' }}
    </button>
  </form>
  <div class="error" *ngIf="error">{{ error }}</div>
</div>

// typescript/native-auth/react-nextjs-sample/src/app/reset-password/page.tsx
"use client";

import { useEffect, useState } from "react";
import { customAuthConfig } from "../../config/auth-config";
import { styles } from "./styles/styles";
import { InitialForm } from "./components/InitialForm";
import { CodeForm } from "./components/CodeForm";
import { NewPasswordForm } from "./components/NewPasswordForm";
import {
    CustomAuthPublicClientApplication,
    ICustomAuthPublicClientApplication,
    ResetPasswordCodeRequiredState,
    ResetPasswordPasswordRequiredState,
    ResetPasswordCompletedState,
    AuthFlowStateBase,
    CustomAuthAccountData,
    SignInCompletedState,
} from "@azure/msal-browser/custom-auth";
import { UserInfo } from "../sign-in/components/UserInfo";

export default function ResetPassword() {
    const [app, setApp] = useState<ICustomAuthPublicClientApplication | null>(null);
    const [loadingAccountStatus, setLoadingAccountStatus] = useState(true);
    const [isSignedIn, setSignInState] = useState(false);
    const [email, setEmail] = useState("");
    const [code, setCode] = useState("");
    const [newPassword, setNewPassword] = useState("");
    const [error, setError] = useState("");
    const [loading, setLoading] = useState(false);
    const [resetState, setResetState] = useState<AuthFlowStateBase | null>(null);
    const [resendCountdown, setResendCountdown] = useState(0);
    const [data, setData] = useState<CustomAuthAccountData | undefined>(undefined);

    useEffect(() => {
        const initializeApp = async () => {
            const appInstance = await CustomAuthPublicClientApplication.create(customAuthConfig);
            setApp(appInstance);
        };

        initializeApp();
    }, []);

    useEffect(() => {
        const checkAccount = async () => {
            if (!app) return;

            const accountResult = app.getCurrentAccount();

            if (accountResult.isCompleted()) {
                setSignInState(true);
            }

            setLoadingAccountStatus(false);
        };

        checkAccount();
    }, [app]);

    const handleInitialSubmit = async (e: React.FormEvent) => {
        if (!app) return;

        e.preventDefault();
        setError("");
        setLoading(true);

        const result = await app.resetPassword({
            username: email,
        });

        const state = result.state;

        if (result.isFailed()) {
            if (result.error?.isInvalidUsername()) {
                setError("Invalid email address");
            } else if (result.error?.isUserNotFound()) {
                setError("User not found");
            } else {
                setError(
                    result.error?.errorData.errorDescription || "An error occurred while initiating password reset"
                );
            }
        } else {
            setResetState(state);
        }

        setLoading(false);
    };

    const handleResendCode = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        setLoading(false);

        if (resetState instanceof ResetPasswordCodeRequiredState) {
            const result = await resetState.resendCode();
            const state = result.state;

            if (result.isFailed()) {
                setError(result.error?.errorData.errorDescription || "An error occurred while resending the code");
            } else {
                setResetState(state);
                setResendCountdown(30);
                
                const timer = setInterval(() => {
                    setResendCountdown((prev) => {
                        if (prev <= 1) {
                            clearInterval(timer);
                            return 0;
                        }
                        return prev - 1;
                    });
                }, 1000);
            }
        }
    };

    const handleCodeSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        setLoading(true);

        if (resetState instanceof ResetPasswordCodeRequiredState) {
            const result = await resetState.submitCode(code);
            const state = result.state;

            if (result.isFailed()) {
                if (result.error?.isInvalidCode()) {
                    setError("Invalid verification code");
                } else {
                    setError(result.error?.errorData.errorDescription || "An error occurred while verifying the code");
                }
            } else {
                setResetState(state);
            }
        }

        setLoading(false);
    };

    const handleNewPasswordSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        setError("");
        setLoading(true);

        if (resetState instanceof ResetPasswordPasswordRequiredState) {
            const result = await resetState.submitNewPassword(newPassword);
            const state = result.state;

            if (result.isFailed()) {
                if (result.error?.isInvalidPassword()) {
                    setError("Invalid password");
                } else {
                    setError(result.error?.errorData.errorDescription || "An error occurred while setting new password");
                }
            } else {
                setResetState(state);

                if (state instanceof ResetPasswordCompletedState) {
                    await handleAutoSignIn(state);
                }
            }
        }

        setLoading(false);
    };

    const handleAutoSignIn = async (resetState: ResetPasswordCompletedState) => {
        setError("");

        if (resetState instanceof ResetPasswordCompletedState) {
            const result = await resetState.signIn();
            const state = result.state;

            if (result.isFailed()) {
                setError(result.error?.errorData?.errorDescription || "An error occurred during auto sign-in");
            }
            if (result.isCompleted()) {
                setData(result.data);
                setResetState(state);
            }
        }
    };

    const renderForm = () => {
        if (loadingAccountStatus) {
            return;
        }

        if (isSignedIn) {
            return (
                <div style={styles.signed_in_msg}>Please sign out before processing the password reset.</div>
            );
        }

        if (resetState instanceof ResetPasswordPasswordRequiredState) {
            return (
                <NewPasswordForm
                    onSubmit={handleNewPasswordSubmit}
                    newPassword={newPassword}
                    setNewPassword={setNewPassword}
                    loading={loading}
                />
            );
        }

        if (resetState instanceof ResetPasswordCodeRequiredState) {
            return <CodeForm onSubmit={handleCodeSubmit} code={code} setCode={setCode} loading={loading} onResendCode={handleResendCode} resendCountdown={resendCountdown} />;
        }

        if (resetState instanceof ResetPasswordCompletedState) {
            return <div style={styles.signed_in_msg}>Password reset completed! Signing you in automatically...</div>;
        }

        if (resetState instanceof SignInCompletedState) {
            return <UserInfo userData={data} />;
        }

        return (
            <InitialForm
                onSubmit={handleInitialSubmit}
                email={email}
                setEmail={setEmail}
                loading={loading}
            />
        );
    }

    return (
        <div style={styles.container}>
            <h2 style={styles.h2}>Reset Password</h2>
            {renderForm()}
            {error && <div style={styles.error}>{error}</div>}
        </div>
    );
}
